name: SwitchBot-Push


jobs:
  run:
    runs-on: ubuntu-latest  # Linuxに戻します
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run Python Script
        env:
          SB_TOKEN: ${{ secrets.SB_TOKEN }}
          SB_SECRET: ${{ secrets.SB_SECRET }}
          GRAFANA_URL: ${{ secrets.GRAFANA_URL }}
          GRAFANA_USER: ${{ secrets.GRAFANA_USER }}
          GRAFANA_TOKEN: ${{ secrets.GRAFANA_TOKEN }}
        run: python fetch_data.py  # ここでPythonを呼ぶように戻す
