name: SwitchBot-Push
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - run: pip install requests prometheus-pb python-snappy
      - name: Run Script
        env:
          SB_TOKEN: ${{ secrets.SB_TOKEN }}
          SB_SECRET: ${{ secrets.SB_SECRET }}
          GRAFANA_URL: ${{ secrets.GRAFANA_URL }}
          GRAFANA_USER: ${{ secrets.GRAFANA_USER }}
          GRAFANA_TOKEN: ${{ secrets.GRAFANA_TOKEN }}
        run: python fetch_data.py
